version: '3'

services:
  mysql:
    image: 'mysql:latest'
    container_name: 'mysql'
    ports:
      - 3306:3306
    networks:
      - database
    env_file:
      - mysql.env
    volumes:
      - /Users/jaylen/database/mysql/conf:/etc/mysql
      - /Users/jaylen/database/mysql/logs:/var/log/mysql
      - /Users/jaylen/database/mysql/data:/var/lib/mysql
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
        '--max_connections=3000'
      ]
    restart: always
  # redis:
  #   image: 'redis:latest'
  #   container_name: 'redis'
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - database
  #   restart: always

networks:
  database:
