ARG VARIANT="lts-alpine"
FROM node:${VARIANT} as builder


RUN apk update --no-cache \
  && apk add bash --no-cache \
  && ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo Asia/Shanghai >/etc/timezone


RUN npm config set registry https://registry.npm.taobao.org \
  && npm install whistle -g
